[package]
name = "smatrix"
version = "0.1.0"
authors = ["Shizcow <pohl.devin@gmail.com>"]
edition = "2018"

[dependencies]
json = "0.12.4"
curl = "0.4.28"
scraper = "0.11.0"
ncurses = "5.99.0"
rand = "0.7.3"