[package]
name = "smatrix"
version = "1.1.1"
authors = ["Shizcow <pohl.devin@gmail.com>"]
edition = "2018"

[dependencies]
json = "0.12.4"
curl = "0.4.28"
scraper = "0.11.0"
rand = "0.7.3"
matrixise = "2.0.0"